Models/Context/BlogContext.cs
using Microsoft.EntityFrameworkCore;
using MVCStartApp.Models.Db;

namespace MVCStartApp.Models.Context
{
    public class BlogContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }

        public BlogContext(DbContextOptions<BlogContext> options) : base(options)
        {       
            Database.EnsureCreated();
        }
    }
}

Models/Db/Feedback.cs
using System;

namespace MVCStartApp.Models.Db
{
    public class Feedback
    {
        public Guid Id { get; set; }

        public string Text { get; set; }

        public string From { get; set; }

    }
}

Models/Db/Request.cs
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace MVCStartApp.Models.Db
{
    [Table("Requests")]
    public class Request
    {
        public Guid Id { get; set; }
        public DateTime Date { get; set; }
        public string Url { get; set; }
    }
}

Models/Db/User.cs
using System;

namespace MVCStartApp.Models.Db
{
    public class User
    {
        public Guid Id { get; set; }
        public string Firstname { get; set; }

        public string Lastname { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MVCStartApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using MVCStartApp.Models;
using MVCStartApp.Models.Db;
using MVCStartApp.Repository.Interfaces;
using System;
using System.Diagnostics;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace MVCStartApp.Controllers
{
    public class FeedbackController : Controller
    {
        public IFeedbackRepository _feedbackRepository { get; set; }

        public FeedbackController(IFeedbackRepository feedbackRepository)
        { 
            _feedbackRepository = feedbackRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Feedback feedback)
        {
            await _feedbackRepository.Add(feedback);
            return StatusCode(200, $"{feedback.From}, благодарим за отзыв!");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var feedbacks = await _feedbackRepository.GetFeedbacks();
            return View(feedbacks);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCStartApp.Models;
using MVCStartApp.Models.Db;
using MVCStartApp.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCStartApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogRepository _blogRepository;

        public HomeController(ILogger<HomeController> logger, IBlogRepository blogRepository)
        {
            _logger = logger;
            _blogRepository = blogRepository;
        }

        public async Task<IActionResult> IndexAsync()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using MVCStartApp.Repository.Interfaces;
using System.Threading.Tasks;

namespace MVCStartApp.Controllers
{
    public class RequestController : Controller
    {
        private readonly IRequestRepository _requestRepository;

        public RequestController(IRequestRepository requestRepository)
        {
            _requestRepository = requestRepository;
        }

        public async Task<IActionResult> Index()
        {
            var requests = await _requestRepository.GetRequests();
            return View(requests);
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCStartApp.Models.Db;
using MVCStartApp.Repository.Interfaces;
using System.Threading.Tasks;

namespace MVCStartApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly IBlogRepository _blogRepository;

        public UsersController(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }

        public async Task<ActionResult> Index()
        {
            var authors = await _blogRepository.GetUsers();
            return View(authors);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(User user)
        {
            await _blogRepository.AddUser(user);
            return View(user);
        }
    }
}

Views/Feedback/Add.cshtml
@{
    ViewData["Title"] = "View project authors";
}
<script>

    function ProcessForm() {
        let data = new FormData();

        data.set("From", document.querySelector('[name="From"]').value)
        data.set("Text", document.querySelector('[name="Text"]').value)

        let postRequest = new XMLHttpRequest();
        postRequest.open('POST', document.URL, true); 

        postRequest.send(data);

        postRequest.onload = function () {


            let element = document.getElementsByClassName("container")[1];
            element.children[0].remove();

            let paragraph = document.createElement("h5");
            paragraph.style = "text-align : center"
            paragraph.innerText = this.response;

            element.appendChild(document.createElement("br"))
            element.appendChild(paragraph)
        };
    }

</script>
<style>
    table {
        border-spacing: 0 15px;
        align-self: center;
    }

    th {
        background-color: #4287f5;
        color: white;
    }

    th,
    td {
        width: 150px;
        text-align: center;
        border: none;
        padding: 5px;
    }

    h2 {
        color: #4287f5;
    }

    .submit-button {
        position: absolute;
        margin-left: 140px;
    }
</style>

<div id="main-block" class="text-center">
    <div>
        <h3 style="text-align: left">Оставьте отзыв о проекте здесь</h3>
        <br>
        <table>
            <tr>
                <td>Ваше имя</td>
                <td><input type="text" name="From" /> </td>
            </tr>
            <tr>
                <td>Ваш отзыв</td>
                <td><input type="text" name="Text" /></td>
            </tr>
        </table>
        <br>
        <div class="submit-button">
            <input type="submit" value="Отправить" onclick="ProcessForm()" />
        </div>
    </div>
</div>

Views/Feedback/Index.cshtml
@{
    ViewData["Title"] = "View project authors";
}
<style>
    table {
        border-spacing: 0 15px;
        align-self: center;
    }

    th {
        background-color: #4287f5;
        color: white;
    }

    th,
    td {
        width: 150px;
        text-align: center;
        border: 1px solid black;
        padding: 5px;
    }

    h2 {
        color: #4287f5;
    }
</style>

<div class="text-center">
    <h2 class="display-4" style="text-align: left">Список запросов</h2>
    <br>
    <table>
        <tr>
            <td>Имя</td>
            <td>Содержание Отзыва</td>
        </tr>
        @foreach (var feedback in Model)
        {
            <tr>
                <td>@feedback.From</td>
                <td>@feedback.Text</td>
            </tr>
        }
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Request/Index.cshtml
@{
    ViewData["Title"] = "View project authors";
}
<style>
    table {
        border-spacing: 0 15px;
        align-self: center;
    }

    th {
        background-color: #4287f5;
        color: white;
    }

    th,
    td {
        width: 150px;
        text-align: center;
        border: 1px solid black;
        padding: 5px;
    }

    h2 {
        color: #4287f5;
    }
</style>

<div class="text-center">
    <h2 class="display-4" style="text-align: left">Список запросов</h2>
    <br>
    <table>
        <tr>
            <td>Дата запрос</td>
            <td>Содержание</td>
            <td>Идентификатор</td>
        </tr>
        @foreach (var request in Model)
        {
            <tr>
                <td>@request.Date</td>
                <td>@request.Url</td>
                <td>@request.Id</td>
            </tr>
        }
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCStartApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCStartApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Feedback" asp-action="Add">Contact us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Feedback" asp-action="Index">Our Feedbacks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCStartApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Users/Index.cshtml
@{
   ViewData["Title"] = "View project authors";
}
<style>
     table {
       border-spacing: 0 15px;
       align-self: center;
     }
     th {
       background-color: #4287f5;
       color: white;
     }
     th,
     td {
       width: 150px;
       text-align: center;
       border: 1px solid black;
       padding: 5px;
     }
     h2 {
       color: #4287f5;      
     }
   </style>
 
<div class="text-center">
    <h2 class="display-4" style="text-align: left">Пользователи проекта</h2>
    <br>
    <table>
        <tr>
            <td>Идентификатор</td>
            <td>Имя</td>
            <td>Дата регистрации</td>
        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.Firstname</td>
                <td>@user.CreatedDate</td>
            </tr>
        }
    </table>
</div>

Views/Users/Register.cshtml
@{
    ViewData["Title"] = "Регистрация нового пользователя.";
}

<style>
    table {
        border-spacing: 0 15px;
        align-self: center;
    }

    th {
        background-color: #4287f5;
        color: white;
    }

    th,
    td {
        width: 150px;
        text-align: center;
        border: none;
        padding: 5px;
    }

    h2 {
        color: #4287f5;
    }

    .submit-button {
        position: absolute;
        margin-left: 140px;
    }
</style>

<div class="text-center">
    <div>
        @if (Model == null)
        {
            <h3 style="text-align: left">Добро пожаловать в наш блог!</h3>
            <br>

            <form method="post">
                <table>
                    <tr>
                        <td>Имя:</td>
                        <td><input type="text" name="FirstName" /> </td>
                    </tr>
                    <tr>
                        <td>Фамилия:</td>
                        <td><input type="text" name="LastName" /></td>
                    </tr>
                </table>
                <br>
                <div class="submit-button">
                    <input type="submit" value="Регистрация" />
                </div>
            </form>
        }
        else
        {
            @await Html.PartialAsync("_Thanks")
        }
    </div>
</div>

Views/Users/_Thanks.cshtml
<div class="text-center">
    <br>
    <div>
        <br>
        <p>@Model.Firstname, спасибо за регистрацию!</p>
    </div>
</div>  